name: Build and Deploy Website

on: [pull_request, push, 'workflow_dispatch']
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Hugo
        run: |
          sudo apt install hugo
          hugo version
      - name: Build
        run: |
          cd ./store
          hugo --minify
          ls public
