name: Build and Deploy Website

on: [pull_request, push, 'workflow_dispatch']
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Hugo
        run: |
          curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest  | grep  browser_download_url  | grep amd64.deb  | grep -v extended  | cut -d '"' -f 4  | wget -i -
          sudo dpkg -i hugo*amd64.deb
          hugo version
      - name: Build
        run: |
          cd ./store
          hugo --minify
          ls public
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: |
            ./store/public